# Generated by Django 5.1.1 on 2025-10-01 22:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Subtítulo')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Imagen')),
                ('link', models.URLField(blank=True, verbose_name='Enlace')),
                ('button_text', models.CharField(default='Ver más', max_length=50, verbose_name='Texto del botón')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StoreConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Clothing Store', max_length=100, verbose_name='Nombre de la tienda')),
                ('logo', models.ImageField(blank=True, upload_to='config/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, upload_to='config/', verbose_name='Favicon')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('about_us', models.TextField(blank=True, verbose_name='Sobre nosotros')),
                ('shipping_info', models.TextField(blank=True, verbose_name='Información de envío')),
                ('return_policy', models.TextField(blank=True, verbose_name='Política de devoluciones')),
                ('color_primary', models.CharField(default='#00D9FF', help_text='Formato hexadecimal: #00D9FF', max_length=7, verbose_name='Color Principal (Botones, Acentos)')),
                ('color_background', models.CharField(default='#000000', help_text='Formato hexadecimal: #000000', max_length=7, verbose_name='Color de Fondo Principal')),
                ('color_cards', models.CharField(default='#1F1F1F', help_text='Formato hexadecimal: #1F1F1F', max_length=7, verbose_name='Color de Tarjetas y Secciones')),
                ('color_text', models.CharField(default='#FFFFFF', help_text='Formato hexadecimal: #FFFFFF', max_length=7, verbose_name='Color de Texto')),
                ('color_text_secondary', models.CharField(default='#FFFFFF', help_text='Formato hexadecimal: #FFFFFF', max_length=7, verbose_name='Color de Texto Secundario')),
                ('color_navbar', models.CharField(default='#000000', help_text='Formato hexadecimal: #000000', max_length=7, verbose_name='Color del Header/Navbar')),
                ('color_footer', models.CharField(default='#000000', help_text='Formato hexadecimal: #000000', max_length=7, verbose_name='Color del Footer')),
                ('color_icons', models.CharField(default='#00D9FF', help_text='Formato hexadecimal: #00D9FF', max_length=7, verbose_name='Color de Iconos')),
                ('opacity_background', models.IntegerField(default=100, help_text='0-100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Opacidad del Fondo (%)')),
                ('opacity_cards', models.IntegerField(default=20, help_text='0-100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Opacidad de Tarjetas (%)')),
                ('opacity_navbar', models.IntegerField(default=60, help_text='0-100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Opacidad del Navbar (%)')),
                ('opacity_footer', models.IntegerField(default=60, help_text='0-100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Opacidad del Footer (%)')),
                ('background_image', models.ImageField(blank=True, help_text='Imagen de fondo con efecto blur al hacer scroll', upload_to='config/', verbose_name='Imagen de Fondo')),
                ('background_blur_amount', models.IntegerField(default=20, help_text='0-50 píxeles', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Cantidad de Blur (px)')),
            ],
            options={
                'verbose_name': 'Configuración de la Tienda',
                'verbose_name_plural': 'Configuración de la Tienda',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='Imagen')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacada')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='store.category', verbose_name='Categoría padre')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio con descuento')),
                ('image_main', models.ImageField(upload_to='products/', verbose_name='Imagen principal')),
                ('image_2', models.ImageField(blank=True, upload_to='products/', verbose_name='Imagen 2')),
                ('image_3', models.ImageField(blank=True, upload_to='products/', verbose_name='Imagen 3')),
                ('image_4', models.ImageField(blank=True, upload_to='products/', verbose_name='Imagen 4')),
                ('gender', models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer'), ('U', 'Unisex')], default='U', max_length=1, verbose_name='Género')),
                ('sizes', models.CharField(help_text='Ej: S,M,L,XL', max_length=100, verbose_name='Tallas disponibles')),
                ('colors', models.CharField(help_text='Ej: Rojo,Azul,Negro', max_length=200, verbose_name='Colores disponibles')),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('is_new', models.BooleanField(default=True, verbose_name='Nuevo')),
                ('is_sale', models.BooleanField(default=False, verbose_name='En oferta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('views', models.IntegerField(default=0, verbose_name='Vistas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-created_at'],
            },
        ),
    ]
