# Generated by Django 5.1.1 on 2025-10-01 23:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.CharField(blank=True, help_text='Ej: 85% Poliéster, 15% Spandex', max_length=300, verbose_name='Composición'),
        ),
        migrations.AddField(
            model_name='product',
            name='fit_type',
            field=models.CharField(choices=[('PERFORMANCE', 'Performance Fit'), ('REGULAR', 'Regular Fit'), ('COMFORT', 'Comfort Fit')], default='REGULAR', max_length=20, verbose_name='Tipo de Ajuste'),
        ),
        migrations.AddField(
            model_name='product',
            name='sport',
            field=models.CharField(choices=[('RUNNING', 'Running'), ('CYCLING', 'Ciclismo'), ('FITNESS', 'Fitness'), ('TRAINING', 'Training'), ('TRIATHLON', 'Triatlón'), ('OUTDOOR', 'Outdoor'), ('SWIMMING', 'Natación'), ('YOGA', 'Yoga')], default='TRAINING', max_length=20, verbose_name='Deporte'),
        ),
        migrations.AddField(
            model_name='product',
            name='uv_protection',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Factor UV'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_grams',
            field=models.IntegerField(blank=True, null=True, verbose_name='Peso (gramos)'),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='manifesto_text',
            field=models.TextField(blank=True, default='El deporte está en nuestro ADN\nExcelencia en cada puntada\nTecnología que no te limita, te impulsa', verbose_name='Texto Manifiesto'),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='slogan',
            field=models.CharField(blank=True, default='Ropa diseñada para los deportistas más exigentes', max_length=300, verbose_name='Slogan'),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='tiktok',
            field=models.URLField(blank=True, verbose_name='TikTok'),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='youtube',
            field=models.URLField(blank=True, verbose_name='YouTube'),
        ),
        migrations.AlterField(
            model_name='storeconfiguration',
            name='about_us',
            field=models.TextField(blank=True, default='El deporte está en nuestro ADN. Ropa diseñada para los deportistas más exigentes que están en busca de su mejor compañero para la aventura.', verbose_name='Sobre nosotros'),
        ),
        migrations.AlterField(
            model_name='storeconfiguration',
            name='store_name',
            field=models.CharField(default='WARSTKI®', max_length=100, verbose_name='Nombre de la tienda'),
        ),
    ]
