# Generated by Django 5.1.1 on 2025-10-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_composition_product_fit_type_product_sport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('video_file', models.FileField(help_text='Formatos recomendados: MP4, WebM', upload_to='videos/', verbose_name='Archivo de Video')),
                ('thumbnail', models.ImageField(blank=True, help_text='Imagen de previsualización del video', upload_to='video_thumbnails/', verbose_name='Miniatura')),
                ('order', models.IntegerField(default=0, help_text='Los videos se mostrarán en orden ascendente', verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
