# Generated by Django 5.1.1 on 2025-10-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconfiguration',
            name='section_subtitle_custom',
            field=models.TextField(blank=True, default='Diseña tu propia ropa deportiva con colores y logos personalizados', help_text='Descripción de personalización', verbose_name='Subtítulo Custom'),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='section_subtitle_hero',
            field=models.CharField(blank=True, default='NEW ERA', help_text='Subtítulo destacado del hero', max_length=200, verbose_name='Subtítulo Hero'),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='section_subtitle_new_products',
            field=models.TextField(blank=True, default='Lo último en tecnología deportiva italiana. Rendimiento que supera marcas que cobran el doble.', help_text='Descripción de productos nuevos', verbose_name='Subtítulo Productos Nuevos'),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='section_subtitle_newsletter',
            field=models.TextField(blank=True, default='Recibe ofertas exclusivas, lanzamientos y consejos de entrenamiento', help_text='Descripción del newsletter', verbose_name='Subtítulo Newsletter'),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='section_subtitle_sale',
            field=models.TextField(blank=True, default='Descuentos increíbles en tu ropa técnica favorita', help_text='Descripción de la sección de ofertas', verbose_name='Subtítulo Ofertas'),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='section_subtitle_sports',
            field=models.TextField(blank=True, default='Ropa técnica especializada para cada disciplina deportiva', help_text='Descripción de la sección de deportes', verbose_name='Subtítulo Sección Deportes'),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='section_subtitle_sustainability',
            field=models.TextField(blank=True, default='Materiales con químicos seguros para personas y el ambiente. Porque el planeta también es nuestro campo de juego.', help_text='Descripción de sostenibilidad', verbose_name='Subtítulo Sostenibilidad'),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='section_subtitle_videos',
            field=models.TextField(blank=True, default='Vive la energía de nuestro deporte: donde la tecnología, la pasión y el diseño se mezclan para dar vida a cada prenda.', help_text='Descripción de la sección de videos', verbose_name='Subtítulo Sección Videos'),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='section_title_custom',
            field=models.CharField(blank=True, default='WARSTKI Custom', help_text='Título de la sección de personalización', max_length=200, verbose_name='Título Custom'),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='section_title_hero',
            field=models.CharField(blank=True, default='NUEVA COLECCIÓN', help_text='Título principal del hero', max_length=200, verbose_name='Título Hero'),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='section_title_new_products',
            field=models.CharField(blank=True, default='Nueva Colección NEW ERA', help_text='Título de la sección de productos nuevos', max_length=200, verbose_name='Título Productos Nuevos'),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='section_title_newsletter',
            field=models.CharField(blank=True, default='Únete a la Comunidad WARSTKI', help_text='Título del newsletter', max_length=200, verbose_name='Título Newsletter'),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='section_title_sale',
            field=models.CharField(blank=True, default='Ofertas Especiales', help_text='Título de la sección de ofertas', max_length=200, verbose_name='Título Ofertas'),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='section_title_sports',
            field=models.CharField(blank=True, default='Encuentra Tu Deporte', help_text='Título de la sección de categorías deportivas', max_length=200, verbose_name='Título Sección Deportes'),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='section_title_sustainability',
            field=models.CharField(blank=True, default='Compromiso Sostenible', help_text='Título de la sección de sostenibilidad', max_length=200, verbose_name='Título Sostenibilidad'),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='section_title_videos',
            field=models.CharField(blank=True, default='Experiencia WARSTKI', help_text='Título de la sección de videos', max_length=200, verbose_name='Título Sección Videos'),
        ),
    ]
