# Generated by Django 5.1.1 on 2025-10-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_storeconfiguration_section_subtitle_custom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconfiguration',
            name='hero_background_image',
            field=models.ImageField(blank=True, help_text='Imagen de fondo para la sección principal/hero de Nueva Colección', upload_to='config/hero/', verbose_name='Imagen de Fondo - Nueva Colección'),
        ),
    ]
