# Generated by Django 5.1.1 on 2025-10-19 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconfiguration',
            name='about_us_image',
            field=models.ImageField(blank=True, help_text="Imagen para la sección 'Quiénes Somos' (taller, equipo, producción)", upload_to='config/about/', verbose_name='Imagen - Quiénes Somos'),
        ),
    ]
