# Generated by Django 5.1.1 on 2025-10-19 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_storeconfiguration_about_us_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Servicio')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(help_text='Descripción detallada del servicio', verbose_name='Descripción')),
                ('icon', models.CharField(default='fas fa-concierge-bell', help_text="Clase de Font Awesome (ej: 'fas fa-cut', 'fas fa-scissors')", max_length=50, verbose_name='Ícono Font Awesome')),
                ('image', models.ImageField(help_text='Imagen representativa del servicio (recomendado: 800x600px)', upload_to='services/', verbose_name='Imagen del Servicio')),
                ('feature_1', models.CharField(blank=True, max_length=200, verbose_name='Característica 1')),
                ('feature_2', models.CharField(blank=True, max_length=200, verbose_name='Característica 2')),
                ('feature_3', models.CharField(blank=True, max_length=200, verbose_name='Característica 3')),
                ('order', models.IntegerField(default=0, help_text='Los servicios se mostrarán en orden ascendente', verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('layout_reverse', models.BooleanField(default=False, help_text='Marcar para mostrar la imagen a la izquierda y texto a la derecha', verbose_name='Invertir Layout')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['order', 'name'],
            },
        ),
    ]
