# Generated by Django 5.1.1 on 2025-10-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconfiguration',
            name='men_separator_image',
            field=models.ImageField(blank=True, help_text='Imagen de ancho completo que separa la sección de productos destacados de hombre', upload_to='config/separators/', verbose_name='Imagen Separadora - Sección Hombres'),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='women_separator_image',
            field=models.ImageField(blank=True, help_text='Imagen de ancho completo que separa la sección de productos destacados de mujer', upload_to='config/separators/', verbose_name='Imagen Separadora - Sección Mujeres'),
        ),
    ]
