# Generated by Django 5.1.1 on 2025-10-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_storeconfiguration_men_separator_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer'), ('K', 'Niños'), ('U', 'Unisex')], default='U', max_length=1, verbose_name='Género'),
        ),
    ]
