# Generated by Django 5.1.1 on 2025-10-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_product_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_zip',
            field=models.CharField(blank=True, max_length=20, verbose_name='Codigo Postal'),
        ),
    ]
