# Generated by Django 5.1.1 on 2025-10-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_add_shipping_zip'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeritageSliderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ej: La Excelencia', max_length=200, verbose_name='Título')),
                ('title_highlight', models.CharField(blank=True, help_text='Ej: en Textiles (se muestra en color diferente)', max_length=100, verbose_name='Parte Destacada del Título')),
                ('description', models.TextField(help_text='Descripción detallada de la colección', verbose_name='Descripción')),
                ('badge_text', models.CharField(help_text='Ej: Colección Exclusiva', max_length=100, verbose_name='Texto del Badge')),
                ('badge_icon', models.CharField(default='fas fa-crown', help_text="Clase de Font Awesome (ej: 'fas fa-crown', 'fas fa-bolt')", max_length=50, verbose_name='Icono del Badge')),
                ('cta_text', models.CharField(default='Descubrir Colección', max_length=100, verbose_name='Texto del Botón')),
                ('cta_url', models.CharField(help_text='Ej: /productos/ o /categoria/futbol', max_length=500, verbose_name='URL del Botón')),
                ('video_url', models.URLField(blank=True, help_text='URL de YouTube, Vimeo, etc. (opcional)', verbose_name='URL del Video')),
                ('video_file', models.FileField(blank=True, help_text='Carga un video MP4 o WebM como alternativa (opcional)', upload_to='heritage_videos/', verbose_name='Archivo de Video Local')),
                ('video_thumbnail', models.ImageField(blank=True, help_text='Imagen de previsualización del video', upload_to='heritage_thumbnails/', verbose_name='Miniatura del Video')),
                ('gradient_color_1', models.CharField(default='#2d5016', help_text='Formato hexadecimal: #2d5016', max_length=7, verbose_name='Color Gradient 1')),
                ('gradient_color_2', models.CharField(default='#3d6b1f', help_text='Formato hexadecimal: #3d6b1f', max_length=7, verbose_name='Color Gradient 2')),
                ('gradient_color_3', models.CharField(default='#5a9a3d', help_text='Formato hexadecimal: #5a9a3d', max_length=7, verbose_name='Color Gradient 3')),
                ('icon', models.CharField(default='fas fa-shirt', help_text="Clase de Font Awesome (ej: 'fas fa-shirt', 'fas fa-person-running')", max_length=50, verbose_name='Icono Principal')),
                ('order', models.IntegerField(default=0, help_text='Los items se mostrarán en orden ascendente', verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Item Heritage Slider',
                'verbose_name_plural': 'Items Heritage Slider',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_zip',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código Postal'),
        ),
    ]
